Получает данные с сервера. Добавляет авторизацию.
htmlacademy-react/181931-six-cities-simple-11 pull request #9
Opened 2022-12-03 16:54 UTC by Caneklis

2022-12-03 18:28 UTC, klimnikova requested changes

2022-12-03 18:28 UTC, klimnikova commented on project/src/store/api-actions.ts
> +  setTimeout(() => store.dispatch(setError(null)), TIMEOUT_SHOW_ERROR);
мне не нравится такая реализация, потому что ошибок у тебя может быть много. Лучше посмотри в сторону пакета react-toastify. Пока можно оставить, но до сдачи нужно будет доработать

2022-12-03 18:28 UTC, klimnikova commented on project/src/services/process-error-handle.ts
> +  store.dispatch(setError(message));
повторю, что лучше просто все это удалить и воспользоваться сторонним пакетом. Возможно даже сейчас можно сделать, там кода немного

2022-12-03 18:28 UTC, klimnikova commented on project/src/services/api.ts
> +const shouldDisplayError = (response: AxiosResponse) => !!StatusCodeMapping[response.status];
а другие статусы не отображать? странно получается

2022-12-03 18:28 UTC, klimnikova commented on project/src/store/api-actions.ts
> +  } catch {
короче увидела сверху, что ты в interceptors сделал. Обобщать не очень такие вещи, потому что очень часто на разные ошибки разных функций нужно по-разному отрисовывать ui, вот как здесь

2022-12-04 11:17 UTC, Caneklis commented on project/src/store/api-actions.ts
> +    dispatch(redirectToRoute(AppRoute.Login));
1. Опечатался, подразумевалось как раз, что должен быть редирект на главную. Я поменял, но все равно редирект не работает.

2022-12-04 11:19 UTC, Caneklis commented on project/src/store/reducer.ts
> +const initialState: InitialState = {
Возможно про это расскажут на оптимизации, я конечно же хочу это поправить, но сначала хочу все базовые выполнить.

2022-12-07 18:00 UTC, klimnikova approved these changes

2022-12-07 18:01 UTC, merged